spring.datasource.url=jdbc:postgresql://dpg-d97dcabtqb8s7382fh50-a:5432/banco_tcfg
spring.datasource.username=banco_tcfg_user
spring.datasource.password=8UAJrfNTXV8cdciKeaf6xHJGawoayv1r

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false

jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXPIRATION}
